# Generated by Django 3.2.6 on 2021-08-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydatas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythondata',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
