# Generated by Django 3.1.7 on 2021-03-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificatedata',
            old_name='description',
            new_name='link',
        ),
    ]
