# Generated by Django 3.2.6 on 2021-08-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificatedata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatedata',
            name='link',
            field=models.CharField(max_length=20000),
        ),
    ]
