# Generated by Django 3.2.6 on 2021-08-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdatas', '0002_auto_20210326_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdatas',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
